### ISSUE TITLE
Permissions when creating output folder

### ISSUE THREAD

**Issue by jimafisk** [parnic/go-assetprecompiler#1]
Thanks for sharing this project @parnic, it seems to be exactly what I'm looking for! I have a simple setup in my `func main()` that looks like this:
```go
precompiler.Compile(precompiler.Config{
  Files: []string{
    "assets/css/main.css",
    "assets/css/components/nav.css",
  },
  Minify:    true,
  OutputDir: "assets/public/",
})
```
When I run `go run .` to compile my project and start up the webserver, if the folder doesn't exist previously, it creates a new folder at `assets/public/`. However this directory has no permissions on it so it loses the ability to create the `assets/public/css` subfolder. If I manually run `chmod -R 777 assets/public/` and then do `go run .` again, this time it's able to create the `assets/public/css` subfolder, but the new folder is also not given any permissions so it's unable to create the css file. If I manually change permissions on this folder via `chmod -R 777 assets/public/css/` and run `go run .` one more time, it now creates a file that looks something like `app-4b19fcc789a5a38eff577d18f2f343aee38dbc3ea4e040cd665d27f9bbc29869.min.css`.

Is there something I should be doing in my Go project setup to fix this permissions issue, or do I need to manually update directory permissions like I did above? Thanks!

**Comment by parnic** [comment]
Thanks for using the project and for providing this feedback. I only tested this on Windows, so I neglected to verify permissions problems like this. I'll see what I can do.
