### ISSUE TITLE
Referencing fingerprinted assets in template

### ISSUE THREAD

**Issue by jimafisk** [parnic/go-assetprecompiler#2]
In the [README.md](https://github.com/parnic/go-assetprecompiler/blob/master/README.md) it mentions you can:

> create a template function to retrieve the correct filenames so you don't have to update your template every time you re-generate.

Is there an example of how to do this and reference that file name hash in a template?

**Comment by parnic** [comment]
The naive version of this, using gin-gonic, might look like having this in your template:
```html
<link rel="stylesheet" href="/assets/css/app-{{.cssHash}}.min.css">
```
with rendering the page and providing that variable:
```golang
r := gin.Default()
r.GET("/", func(c *gin.Context) {
	precompileResult, _ := precompiler.Compile(precompiler.Config{
		Files: []string{
			"assets/css/bootstrap.min.css",
			"assets/css/font-awesome.min.css",
			"assets/css/application.css",
		},
		Minify: true,
	})

	c.HTML(http.StatusOK, "myTemplate", gin.H{"cssHash": precompileResult[precompiler.CSS].Hash)
}
```
Obviously you wouldn't actually want to run the precompiler for every page request and you'd want to check errors, but hopefully that gives the general idea.

**Comment by jimafisk** [comment]
Thanks @parnic! That helped me get the hash values:

```
cssHash := precompileResult[precompiler.CSS].Hash
jsHash := precompileResult[precompiler.JS].Hash  
```
